name: opentnsim
channels:
  - conda-forge
dependencies:
  - python=3.9
  - git=2
  - pip=22
  - click=7
  - geojson=2
  - geopandas=0.10
  - networkx>=2.6
  - numpy=1
  - pandas=1
  - pyproj=3
  - requests=2
  - scipy=1
  - setuptools
  - shapely>=2
  - geos=3
  - tqdm=4
  - jupyter=1
  - notebook=6
  - jupyterlab=3
  - ipyleaflet
  - ipython=7
  - matplotlib=3
  - pint=0.18
  - plotly=5
  - simplekml=1
  - nose=1
  - sphinx_rtd_theme=1
  - Dill=0.3
  - pytest=6
  - pytest-cov=3
  - pytest-timeout=2
  - pytest-datadir=1
  - nbmake=1
  - pyyaml=6
  - openpyxl=3
  - folium=0.12
  - colorcet=3
  - gdal=3

  - pip:
    - simpy
